/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        // Nueva Paleta Corporativa Oficial
        primary: {
          DEFAULT: '#2563EB',
          dark: '#1E3A8A',
          light: '#60A5FA',
          50: '#EFF6FF',
          100: '#DBEAFE',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
          800: '#1E40AF',
          900: '#1E3A8A',
        },
        dark: '#1E3A8A',
        secondary: {
          DEFAULT: '#06B6D4',
          light: '#67E8F9',
          dark: '#0E7490',
          50: '#ECFEFF',
          100: '#CFFAFE',
          500: '#06B6D4',
          600: '#0891B2',
          700: '#0E7490',
        },
        success: {
          DEFAULT: '#10B981',
          light: '#34D399',
          dark: '#047857',
          50: '#ECFDF5',
          100: '#D1FAE5',
          500: '#10B981',
          600: '#059669',
        },
        premium: {
          DEFAULT: '#8B5CF6',
          light: '#A78BFA',
          dark: '#6D28D9',
          50: '#F5F3FF',
          100: '#EDE9FE',
          500: '#8B5CF6',
          600: '#7C3AED',
        },
        reward: {
          DEFAULT: '#F59E0B',
          light: '#FBBF24',
          dark: '#B45309',
          50: '#FFFBEB',
          100: '#FEF3C7',
          500: '#F59E0B',
          600: '#D97706',
        },
        background: '#F8FAFC',
        surface: '#FFFFFF',
        text: {
          DEFAULT: '#0F172A',
          muted: '#64748B',
          light: '#94A3B8',
        },

        // Tokens compatibles con el diseño de componentes existentes
        'primary-container': '#DBEAFE',
        'on-primary': '#FFFFFF',
        'primary-fixed': '#DBEAFE',
        'on-primary-container': '#1E3A8A',
        'secondary-container': '#CFFAFE',
        'secondary-fixed': '#CFFAFE',
        'secondary-fixed-dim': '#67E8F9',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#0E7490',
        'on-secondary-fixed': '#083344',
        'on-secondary-fixed-variant': '#0E7490',
        'on-surface': '#0F172A',
        'on-surface-variant': '#475569',
        'surface-variant': '#F1F5F9',
        'surface-container': '#F8FAFC',
        'surface-container-high': '#F1F5F9',
        'surface-container-highest': '#E2E8F0',
        'surface-container-low': '#FAFAFA',
        'surface-container-lowest': '#FFFFFF',
        'surface-bright': '#FFFFFF',
        'surface-dim': '#E2E8F0',
        'surface-tint': '#2563EB',
        outline: '#CBD5E1',
        'outline-variant': '#E2E8F0',
        error: '#EF4444',
        'error-container': '#FEE2E2',
        'on-error': '#FFFFFF',
        'on-error-container': '#991B1B',
        tertiary: '#8B5CF6',
        'tertiary-container': '#EDE9FE',
        'tertiary-fixed': '#EDE9FE',
        'tertiary-fixed-dim': '#C4B5FD',
        'on-tertiary': '#FFFFFF',
        'on-tertiary-container': '#5B21B6',
        'on-tertiary-fixed': '#2E1065',
        'on-tertiary-fixed-variant': '#6D28D9',
        'inverse-surface': '#0F172A',
        'inverse-primary': '#93C5FD',
        'inverse-on-surface': '#F8FAFC'
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px'
      },
      spacing: {
        'section-gap': '80px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        base: '8px',
        gutter: '24px',
        'margin-desktop': '40px'
      },
      fontFamily: {
        'headline-lg-mobile': ['Manrope'],
        'headline-lg': ['Manrope'],
        caption: ['Manrope'],
        'headline-xl': ['Manrope'],
        'body-md': ['Manrope'],
        'headline-md': ['Manrope'],
        'body-lg': ['Manrope'],
        'label-md': ['Hanken Grotesk']
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }]
      }
    }
  },
  plugins: []
};
